export enum ComicsActionTypes {
    FETCH_COMICS = 'FETCH_COMICS',
    FETCH_COMICS_START = 'FETCH_COMICS_START',
    FETCH_COMICS_SUCCESS = 'FETCH_COMICS_SUCCESS',
    FETCH_COMICS_ERROR = 'FETCH_COMICS_ERROR',
}